/** @type {import('tailwindcss').Config} */
// Tokens del sistema de diseño "Brasa Viva" (.claude/plan/01-design-system.md), tema claro.
// El modo oscuro se decide en la fase 05 (variables CSS por tema o pares `-dark`).
module.exports = {
  content: ['./src/**/*.{js,jsx,ts,tsx}'],
  presets: [require('nativewind/preset')],
  theme: {
    extend: {
      colors: {
        'surface-100': '#FFF8F0',
        'surface-200': '#FFFBF6',
        'surface-300': '#FDEEDF',
        border: '#F1DFCB',
        ink: '#2B1B12',
        'ink-muted': '#6E6153',
        'ink-faint': '#8A7862',
        'ink-on-fill': '#2B1B12',
        ember: '#FF6B35',
        'ember-strong': '#C2410C',
        'ember-glow': '#FFB238',
        'focus-ring': '#C2410C',
        success: '#15803D',
        'success-fill': '#15803D',
        'on-success': '#FFFFFF',
        'success-soft': '#DCF5E3',
        warning: '#B45309',
        'warning-fill': '#B45309',
        'on-warning': '#FFFFFF',
        'warning-soft': '#FFE9C2',
        error: '#C0392B',
        'error-fill': '#C0392B',
        'on-error': '#FFFFFF',
        'error-soft': '#FBDEDB',
        protegido: '#0369A1',
        'protegido-fill': '#0369A1',
        'on-protegido': '#FFFFFF',
        'protegido-soft': '#DBEEFC',
        vacio: '#8A7862',
        'vacio-soft': '#FDEEDF',
        'week-morado': '#7C3AED',
        'week-morado-soft': '#EEE7FD',
        'week-azul': '#2563EB',
        'week-azul-soft': '#E1EBFE',
        'week-turquesa': '#097267',
        'week-turquesa-soft': '#DCF3EF',
        'week-rosa': '#DB2777',
        'week-rosa-soft': '#FCE4F1',
        'week-verde': '#16A34A',
        'week-verde-soft': '#DEF5E3',
      },
      // Un archivo por peso (@expo-google-fonts), cargados en src/app/_layout.tsx.
      fontFamily: {
        heading: ['Baloo2_700Bold'],
        'heading-extrabold': ['Baloo2_800ExtraBold'],
        'heading-medium': ['Baloo2_500Medium'],
        body: ['Nunito_400Regular'],
        'body-semibold': ['Nunito_600SemiBold'],
        'body-bold': ['Nunito_700Bold'],
        'body-extrabold': ['Nunito_800ExtraBold'],
      },
      fontSize: {
        'display-lg': ['40px', { lineHeight: '44px' }],
        'display-md': ['28px', { lineHeight: '32px' }],
        'heading-lg': ['22px', { lineHeight: '28px' }],
        'heading-md': ['18px', { lineHeight: '24px' }],
        'heading-sm': ['15px', { lineHeight: '20px' }],
        body: ['14px', { lineHeight: '20px' }],
        caption: ['12px', { lineHeight: '16px' }],
        label: ['11px', { lineHeight: '14px', letterSpacing: '0.04em' }],
        button: ['15px', { lineHeight: '20px' }],
      },
      borderRadius: {
        sm: '8px',
        md: '12px',
        lg: '18px',
        xl: '24px',
        full: '999px',
      },
    },
  },
  plugins: [],
};
